global.onlyIntsRegex    = /^[0-9]+$/;
global.usernameRegex    = /^[a-zA-Z0-9]+$/;
global.passwordRegex    = /^[a-zA-Z0-9:.?!@#$%^&*\-=_+\'\";<>,\/]+$/;
global.individNameRegex = /^[\w\d]+$/i;
global.commentRegex     = /^[\w\d.,:;"'-=_+!@#$%^&*0-9 ]+$/i;
global.itemRegex        = /^[\w\d.,:;"'-=_+!@#$%^&*0-9 ]+$/i;
global.shopRegex        = /^[\w\d.,:;"'-=_+!@#$%^&*0-9 ]+$/i;
global.latLngRegex      = /^-?[0-9]{1,3}\.?[0-9]{0,}$/;
global.tipRegex         = /^(%?[0-9]{1,3}\.?[0-9]{0,}|\$?[0-9]{1,}\.?[0-9]{0,})$/;
global.priceRegex       = /^\$?[0-9]+\.?[0-9]{0,}$/;
global.emailRegex       = /[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/;
