global.onlyIntsRegex    = /^[0-9]+$/;
global.usernameRegex    = /^[a-zA-Z0-9]+$/;
global.passwordRegex    = /^[a-zA-Z0-9:.?!@#$%^&*\-=_+\'\";<>,\/]+$/;
global.individNameRegex = /^[\w\d]+$/i;
global.commentRegex     = /^[\w\d]+ [\w\d]+$/i;
global.itemRegex        = /^[\w\d]+ [\w\d]+$/i;
global.shopRegex        = /^[\w\d]+ [\w\d]+$/i;
global.latLngRegex      = /^[0-9]{1,3}\.[0-9]{1,}$/;
global.tipRegex         = /^(%?[0-9]{1,3}\.[0-9]{1,}|\$?[0-9]{1,}\.[0-9]{1,})$/;
global.priceRegex       = /^\$?[0-9]+.[0-9]{1,}$/;
global.emailRegex       = /[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/;
